# Holds http-echo application configuration

# Global ingress settings
ingress:
  enabled: true

# List of http-echo deployments
deployments:
  - name: foo
    responseText: "foo"
    replicaCount: 3
    image:
      repository: hashicorp/http-echo
      tag: latest
    service:
      type: ClusterIP
      port: 80
    ingress:
      host: foo.localhost
    resources:
      limits:
        cpu: 1
        memory: 356Mi
      requests:
        cpu: 300m
        memory: 30Mi
  - name: bar
    responseText: "bar"
    replicaCount: 3
    image:
      repository: hashicorp/http-echo
      tag: latest
    service:
      type: ClusterIP
      port: 80
    ingress:
      host: bar.localhost
    resources:
      limits:
        cpu: 1
        memory: 356Mi
      requests:
        cpu: 300m
        memory: 30Mi
